[package]
name = "pluggable"
version = "0.1.0"
authors = ["David Kern <david@mju.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pluggable-macros = { path = "../pluggable-macros" }
